name: Model CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow pandas numpy scikit-learn matplotlib joblib

      - name: Run MLflow Project
        working-directory: ./MLProject
        run: |
          mlflow run . --env-manager=local --experiment-name California_Housing_Basic
